"use client";

import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { AlertCircle, CheckCircle2, Layers3, Loader2, Save, WandSparkles } from "lucide-react";
import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";

import { PageHeader } from "@/components/page-header";
import { ImageDropzone } from "@/components/image-dropzone";
import { PromptPreview } from "@/components/prompt-preview";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { api, getConcepts } from "@/lib/api";
import { accentColors, backgroundFamilies, promptFormats } from "@/lib/constants";
import type { Concept } from "@/lib/types";

interface Generated {
  template: string;
  format: string;
  prompt: string;
  rules_included: string[];
  character_reference: string;
  sections: Array<{ title: string; content: string }>;
  scene_reference_path?: string | null;
  scene_reference_analysis?: string | null;
  left_character?: "boy" | "girl";
}

type SourceMode = "saved" | "new";

const emptyConcept = {
  leftTitle: "",
  rightTitle: "",
  leftScene: "",
  rightScene: "",
  emotionalInsight: "",
  leftSetting: "",
  rightSetting: "",
  leftProps: "",
  rightProps: "",
  sharedEnvironment: "",
  environmentalContrast: "",
};

export default function PromptBuilderPage() {
  return (
    <Suspense fallback={<div className="p-8 text-sm text-muted">Loading prompt builder…</div>}>
      <PromptBuilder />
    </Suspense>
  );
}

function PromptBuilder() {
  const params = useSearchParams();
  const routeConceptId = params.get("concept") ?? "";
  const [sourceMode, setSourceMode] = useState<SourceMode>("saved");
  const [concepts, setConcepts] = useState<Concept[]>([]);
  const [conceptId, setConceptId] = useState(routeConceptId);
  const [inlineConcept, setInlineConcept] = useState(emptyConcept);
  const [format, setFormat] = useState("x-with-you");
  const [leftCharacter, setLeftCharacter] = useState<"boy" | "girl">("boy");
  const [background, setBackground] = useState("warm cream");
  const [accent, setAccent] = useState("muted mustard");
  const [cameraAngle, setCameraAngle] = useState("medium straight-on");
  const [props, setProps] = useState("");
  const [notes, setNotes] = useState("");
  const [risks, setRisks] = useState("");
  const [brandReference, setBrandReference] = useState(false);
  const [sceneReferencePath, setSceneReferencePath] = useState("");
  const [sceneReferenceName, setSceneReferenceName] = useState("");
  const [sceneReferenceAnalysis, setSceneReferenceAnalysis] = useState("");
  const [sceneReferenceNotes, setSceneReferenceNotes] = useState("");
  const [referenceUploading, setReferenceUploading] = useState(false);
  const [referenceError, setReferenceError] = useState("");
  const [referenceAnalysisWarning, setReferenceAnalysisWarning] = useState("");
  const [imageEdit, setImageEdit] = useState(false);
  const [edit, setEdit] = useState({
    unchanged: "Keep the left panel, captions, background, colors, and unaffected characters unchanged.",
    edit_region: "right panel",
    change: "",
    do_not_introduce: "No new anatomy, props, text, colors, or style changes.",
  });
  const [generated, setGenerated] = useState<Generated>();
  const [loading, setLoading] = useState(false);
  const autoGenerated = useRef(false);
  const selected = useMemo(() => concepts.find((item) => item.id === conceptId), [concepts, conceptId]);
  const needsPair = ["split-comic", "x-with-you", "before-after", "dialogue"].includes(format);
  const inlineReady = !imageEdit || Boolean(edit.change.trim());
  const colorsReady = Boolean(background.trim() && accent.trim());
  const canGenerate = !referenceUploading && colorsReady && (sourceMode === "saved" ? Boolean(conceptId) : inlineReady);

  useEffect(() => {
    getConcepts()
      .then(setConcepts)
      .catch((error) => toast.error(error instanceof Error ? error.message : "Could not load concepts"));
  }, []);

  useEffect(() => {
    if (!selected || sourceMode !== "saved") return;
    setFormat(selected.format);
    setLeftCharacter(selected.left_character ?? "boy");
    setBackground(selected.recommended_background_color);
    setAccent(selected.recommended_accent_color);
    setCameraAngle(selected.recommended_camera_angle);
    setProps((selected.props ?? []).join(", "));
    setRisks((selected.execution_risks ?? []).join(", "));
    setNotes(selected.notes ?? selected.novel_angle ?? selected.emotional_insight);
  }, [selected, sourceMode]);

  useEffect(() => {
    if (!selected || sourceMode !== "saved" || params.get("autogenerate") !== "1" || autoGenerated.current) return;
    autoGenerated.current = true;
    setLoading(true);
    api<Generated>("/api/prompts/generate", {
      method: "POST",
      body: JSON.stringify({
        concept_id: selected.id,
        format: selected.format,
        title_pair: selected.title_pair,
        left_character: selected.left_character ?? "boy",
        left_character_action: selected.left_character_action ?? selected.left_scene,
        left_setting: selected.left_setting ?? "",
        left_props: selected.left_props ?? [],
        left_emotion: selected.left_emotion ?? "",
        right_characters: "boy_and_girl",
        right_character_actions: selected.right_character_actions ?? selected.right_scene,
        right_setting: selected.right_setting ?? "",
        right_props: selected.right_props ?? [],
        right_emotion: selected.right_emotion ?? "",
        shared_environment: selected.shared_environment ?? "",
        environmental_contrast: selected.environmental_contrast ?? "",
        left_scene: selected.left_scene,
        right_scene: selected.right_scene,
        emotional_insight: selected.emotional_insight,
        recommended_background_color: selected.recommended_background_color,
        recommended_accent_color: selected.recommended_accent_color,
        recommended_camera_angle: selected.recommended_camera_angle,
        props: selected.props ?? [],
        execution_risks: selected.execution_risks ?? [],
        brand_placement_opportunities: selected.brand_placement_opportunities ?? [],
        composition_notes: selected.notes ?? selected.novel_angle ?? "",
      }),
    })
      .then((result) => {
        setGenerated(result);
        toast.success("Story Library prompt generated");
      })
      .catch((error) => {
        autoGenerated.current = false;
        toast.error(error instanceof Error ? error.message : "Could not generate prompt");
      })
      .finally(() => setLoading(false));
  }, [params, selected, sourceMode]);

  function changeSource(value: string) {
    setSourceMode(value as SourceMode);
    setGenerated(undefined);
    autoGenerated.current = false;
  }

  function updateInline(key: keyof typeof inlineConcept, value: string) {
    setInlineConcept((current) => ({ ...current, [key]: value }));
    setGenerated(undefined);
  }

  async function uploadSceneReference(file: File | null) {
    setGenerated(undefined);
    setSceneReferencePath("");
    setSceneReferenceAnalysis("");
    setReferenceError("");
    setReferenceAnalysisWarning("");
    if (!file) {
      setSceneReferenceName("");
      setSceneReferenceNotes("");
      return;
    }
    setSceneReferenceName(file.name);
    setReferenceUploading(true);
    const form = new FormData();
    form.append("file", file);
    try {
      const uploaded = await api<{ path: string; original_name: string; scene_brief: string; analysis_error?: string | null; analysis_warning?: string | null }>("/api/prompts/reference-image", {
        method: "POST",
        body: form,
      });
      setSceneReferencePath(uploaded.path);
      setSceneReferenceAnalysis(uploaded.scene_brief ?? "");
      setReferenceAnalysisWarning(uploaded.analysis_warning ?? uploaded.analysis_error ?? "");
      if (!conceptId) setSourceMode("new");
      toast.success(uploaded.scene_brief ? "Reference converted into a written scene brief" : "Reference uploaded — add or correct its scene brief below");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Could not upload scene reference";
      setReferenceError(message);
      setSceneReferenceName("");
      toast.error(message);
    } finally {
      setReferenceUploading(false);
    }
  }

  function requestPayload(character: "boy" | "girl" = leftCharacter) {
    const common = {
      format,
      left_character: character,
      right_characters: "boy_and_girl",
      recommended_background_color: background,
      recommended_accent_color: accent,
      recommended_camera_angle: cameraAngle,
      props: split(props),
      execution_risks: split(risks),
      composition_notes: notes,
      product_references: brandReference ? ["uploaded product reference — product identity only"] : [],
      scene_reference_path: sceneReferencePath || null,
      scene_reference_analysis: sceneReferenceAnalysis || null,
      scene_reference_notes: sceneReferenceNotes || null,
      image_edit_mode: imageEdit,
      ...edit,
    };
    if (sourceMode === "saved") return { ...common, concept_id: conceptId };
    return {
      ...common,
      concept_id: null,
      title_pair: { left: inlineConcept.leftTitle, right: inlineConcept.rightTitle },
      left_scene: inlineConcept.leftScene,
      right_scene: inlineConcept.rightScene,
      emotional_insight: inlineConcept.emotionalInsight,
      left_character_action: inlineConcept.leftScene,
      left_setting: inlineConcept.leftSetting,
      left_props: split(inlineConcept.leftProps),
      left_emotion: "Neutral, bored, or gently sad—never happy.",
      right_character_actions: inlineConcept.rightScene,
      right_setting: inlineConcept.rightSetting,
      right_props: split(inlineConcept.rightProps),
      right_emotion: "Warm and connected because the ordinary moment is shared.",
      shared_environment: inlineConcept.sharedEnvironment,
      environmental_contrast: inlineConcept.environmentalContrast,
    };
  }

  async function generate(character: "boy" | "girl" = leftCharacter, silent = false) {
    if (!canGenerate) return;
    setLoading(true);
    try {
      const result = await api<Generated>("/api/prompts/generate", {
        method: "POST",
        body: JSON.stringify(requestPayload(character)),
      });
      setGenerated(result);
      if (!silent) toast.success(sourceMode === "new" ? "New concept prompt generated" : "Production brief generated");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Could not generate prompt");
    } finally {
      setLoading(false);
    }
  }

  function changeLeftCharacter(value: "boy" | "girl") {
    const refreshPreview = Boolean(generated);
    setLeftCharacter(value);
    if (refreshPreview) void generate(value, true);
    else setGenerated(undefined);
  }

  async function save(status: "draft" | "approved") {
    if (!generated) return;
    const inlineTitle = [inlineConcept.leftTitle, inlineConcept.rightTitle].filter(Boolean).join(" / ") || "DINKLY prompt";
    try {
      await api("/api/prompts", {
        method: "POST",
        body: JSON.stringify({
          title: sourceMode === "saved" && selected ? `${selected.title_pair.left} / ${selected.title_pair.right}` : inlineTitle,
          format: generated.format,
          source_storyline_id: sourceMode === "saved" ? conceptId || null : null,
          template: generated.template,
          character_reference: generated.character_reference,
          product_references: brandReference ? ["local product reference"] : [],
          prompt: generated.prompt,
          status,
          approved_by: status === "approved" ? "local creative team" : null,
          qa_notes: sceneReferencePath
            ? `Generated as a DINKLY-universe adaptation of ${sceneReferenceName || "an uploaded scene reference"}; character identity and style remain locked to the official model sheet.`
            : sourceMode === "new" ? "Generated from an inline Prompt Builder concept." : "Generated through DINKLY Creative Studio.",
          left_character: leftCharacter,
        }),
      });
      toast.success(status === "approved" ? "Prompt approved" : "Draft saved");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Could not save prompt");
    }
  }

  return (
    <div className="space-y-7">
      <PageHeader eyebrow="Build" title="Nano Banana prompt builder" description="Use a saved concept or write a new one here, then generate a concise production-ready prompt." />
      <div className="grid gap-6 xl:grid-cols-[460px_1fr]">
        <div className="space-y-4">
          <Card>
            <CardHeader><CardTitle>Prompt brief</CardTitle></CardHeader>
            <CardContent className="space-y-5">
              <Field label="Concept source">
                <Tabs value={sourceMode} onValueChange={changeSource}>
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="saved">Saved concept</TabsTrigger>
                    <TabsTrigger value="new">Create new concept</TabsTrigger>
                  </TabsList>
                </Tabs>
              </Field>

              {sourceMode === "saved" ? (
                <>
                  <Field label="Saved concept">
                    <Select value={conceptId} onChange={(event) => { setConceptId(event.target.value); setGenerated(undefined); autoGenerated.current = false; }}>
                      <option value="">Choose a saved concept</option>
                      {concepts.map((concept) => <option key={concept.id} value={concept.id}>{concept.title_pair.left} / {concept.title_pair.right}</option>)}
                    </Select>
                  </Field>
                  {selected && <div className="rounded-xl border border-mustard/40 bg-mustard/10 p-4 text-xs leading-5"><strong>Loaded concept:</strong> {selected.emotional_insight}</div>}
                  <Field label="Prompt format">
                    <Select value={format} onChange={(event) => { setFormat(event.target.value); setGenerated(undefined); }}>
                      {promptFormats.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}
                    </Select>
                  </Field>
                </>
              ) : (
                <div className="space-y-4 rounded-xl border border-line bg-wash/40 p-4">
                  <Field label="Prompt format">
                    <Select value={format} onChange={(event) => { setFormat(event.target.value); setGenerated(undefined); }}>
                      {promptFormats.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}
                    </Select>
                  </Field>
                  <p className="text-xs leading-5 text-muted">This concept goes directly into the prompt. It does not need to exist in the Concepts dropdown.</p>
                  {needsPair ? (
                    <>
                      <div className="grid grid-cols-2 gap-3">
                        <Field label="Left caption (optional)"><Input value={inlineConcept.leftTitle} onChange={(event) => updateInline("leftTitle", event.target.value)} placeholder="LAUNDRY" /></Field>
                        <Field label="Right caption (optional)"><Input value={inlineConcept.rightTitle} onChange={(event) => updateInline("rightTitle", event.target.value)} placeholder="LAUNDRY WITH YOU" /></Field>
                      </div>
                      <Field label="Left scene (optional · never happy)"><Textarea value={inlineConcept.leftScene} onChange={(event) => updateInline("leftScene", event.target.value)} placeholder="Dinko handles the ordinary activity alone, looking neutral or bored…" /></Field>
                      <Field label="Right scene (optional)"><Textarea value={inlineConcept.rightScene} onChange={(event) => updateInline("rightScene", event.target.value)} placeholder="Dinka and Dinko share the same activity in a warmer version of the same scene…" /></Field>
                    </>
                  ) : (
                    <>
                      <Field label="Caption (optional)"><Input value={inlineConcept.rightTitle} onChange={(event) => updateInline("rightTitle", event.target.value)} placeholder="A short exact caption" /></Field>
                      <Field label="Scene (optional)"><Textarea value={inlineConcept.rightScene} onChange={(event) => updateInline("rightScene", event.target.value)} placeholder="Describe one clear DINKLY moment…" /></Field>
                    </>
                  )}
                  <div className="grid gap-3 sm:grid-cols-2">
                    <Field label="Left setting (optional)"><Input value={inlineConcept.leftSetting} onChange={(event) => updateInline("leftSetting", event.target.value)} placeholder="small indoor party room" /></Field>
                    <Field label="Right setting (optional)"><Input value={inlineConcept.rightSetting} onChange={(event) => updateInline("rightSetting", event.target.value)} placeholder="the same small party room" /></Field>
                    <Field label="Left props (optional)"><Input value={inlineConcept.leftProps} onChange={(event) => updateInline("leftProps", event.target.value)} placeholder="cup, deflated balloons, snack table" /></Field>
                    <Field label="Right props (optional)"><Input value={inlineConcept.rightProps} onChange={(event) => updateInline("rightProps", event.target.value)} placeholder="two cups, floating balloons, snacks" /></Field>
                  </div>
                  <Field label="Shared environment (optional)"><Textarea value={inlineConcept.sharedEnvironment} onChange={(event) => updateInline("sharedEnvironment", event.target.value)} placeholder="What stays visually consistent across both panels…" /></Field>
                  <Field label="Environmental contrast (optional)"><Textarea value={inlineConcept.environmentalContrast} onChange={(event) => updateInline("environmentalContrast", event.target.value)} placeholder="What becomes visually warmer and more active on the right…" /></Field>
                  <Field label="Emotional insight (optional)"><Textarea value={inlineConcept.emotionalInsight} onChange={(event) => updateInline("emotionalInsight", event.target.value)} placeholder="Why this ordinary moment feels more meaningful together…" /></Field>
                </div>
              )}

              <div className="space-y-3 rounded-2xl border border-line bg-wash/40 p-4">
                <div><p className="text-xs font-bold uppercase tracking-wider">Left panel character</p><p className="mt-1 text-xs leading-5 text-muted">Choose who appears alone. The right panel remains Boy DINKLY and Girl DINKLY together.</p></div>
                <div className="grid grid-cols-2 gap-3">
                  <CharacterButton label="Boy DINKLY" detail="Exactly two hair tufts" active={leftCharacter === "boy"} onClick={() => changeLeftCharacter("boy")} />
                  <CharacterButton label="Girl DINKLY" detail="Red bow + connected ponytail" active={leftCharacter === "girl"} onClick={() => changeLeftCharacter("girl")} />
                </div>
                <div className="grid grid-cols-2 gap-3 rounded-xl border border-line bg-white p-3 text-xs"><p><strong>Left:</strong><br />{leftCharacter === "girl" ? "Girl alone" : "Boy alone"}</p><p><strong>Right:</strong><br />Boy + Girl together</p></div>
                {(sourceMode === "saved" ? selected?.left_scene : inlineConcept.leftScene) && <p className="text-xs leading-5 text-muted"><strong>Left scene preview:</strong> {adaptLeftCopy(sourceMode === "saved" ? selected?.left_scene ?? "" : inlineConcept.leftScene, leftCharacter)}</p>}
              </div>

              <div className="flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-800">
                <CheckCircle2 className="size-4" /><span><strong>Character reference locked:</strong> references/dinkly_young.png</span>
              </div>

              <div className="space-y-3 rounded-2xl border border-line bg-white p-4">
                <div>
                  <p className="text-sm font-semibold">Adapt a reference comic into the DINKLY universe</p>
                  <p className="mt-1 text-xs leading-5 text-muted">Optional. The studio analyzes the image into an editable written scene brief. The finished Nano Banana prompt uses that description, so you will not need to upload the reference image again. Official Dinka and Dinko identity, colors, anatomy, markings, and flat artwork always win.</p>
                </div>
                <ImageDropzone
                  onFile={uploadSceneReference}
                  title="Drop a scene-reference comic here"
                  description="PNG, JPG, JPEG, or WEBP. Analyzed locally into a self-contained scene description."
                />
                {referenceUploading && <p className="text-xs font-semibold text-muted">Analyzing the scene locally…</p>}
                {referenceError && <p role="alert" className="text-xs text-red-700">{referenceError}</p>}
                {sceneReferencePath && (
                  <div className="space-y-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4">
                    <p className="text-xs font-semibold text-emerald-900">Written scene brief ready: {sceneReferenceName}</p>
                    <p className="text-xs leading-5 text-emerald-800">The generated prompt will contain this description and the strict DINKLY conversion rules. You do not need to attach the original image in Nano Banana.</p>
                    {referenceAnalysisWarning && <p className="text-xs leading-5 text-amber-800">Automatic analysis was limited: {referenceAnalysisWarning} Review or write the scene brief before generating.</p>}
                    <Field label="Detected scene brief (editable)"><Textarea className="min-h-40" value={sceneReferenceAnalysis} onChange={(event) => { setSceneReferenceAnalysis(event.target.value); setGenerated(undefined); }} placeholder="Describe the source environment, storyline, camera framing, character placement, interaction, and emotion. The final prompt will use this text instead of the image." /></Field>
                    <Field label="Corrections or priorities (optional)"><Textarea value={sceneReferenceNotes} onChange={(event) => { setSceneReferenceNotes(event.target.value); setGenerated(undefined); }} placeholder="Example: Keep the cozy kitchen layout, centered table, and shy-to-warm emotional contrast." /></Field>
                  </div>
                )}
              </div>

              <div className="grid gap-3 sm:grid-cols-2">
                <PresetOrCustomColor label="Shared background" value={background} options={backgroundFamilies} onChange={setBackground} placeholder="e.g. pale apricot or #F6D6C8" />
                <PresetOrCustomColor label="Accent color" value={accent} options={accentColors} onChange={setAccent} placeholder="e.g. muted teal or #7FA9A1" />
              </div>

              <Field label="Camera angle"><Input value={cameraAngle} onChange={(event) => setCameraAngle(event.target.value)} /></Field>
              <Field label="Text settings"><Input value="Bubblebody Neue Regular when captions are used · no quotation marks" readOnly /></Field>
              <Field label="Scene props"><Input value={props} onChange={(event) => setProps(event.target.value)} placeholder="café table, chairs, coffee machine" /></Field>
              <Field label="Composition notes"><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="One clear action per character; keep both on the floor…" /></Field>
              <Field label="Known risks"><Textarea value={risks} onChange={(event) => setRisks(event.target.value)} placeholder="Oversized mugs, sitting on table…" /></Field>
              <Toggle label="A product reference is supplied" checked={brandReference} onChange={setBrandReference} />
              <Toggle label="Edit an existing image" checked={imageEdit} onChange={setImageEdit} />

              {imageEdit && (
                <div className="space-y-3 rounded-xl border border-line p-4">
                  <Field label="Keep unchanged"><Textarea value={edit.unchanged} onChange={(event) => setEdit({ ...edit, unchanged: event.target.value })} /></Field>
                  <Field label="Edit region"><Input value={edit.edit_region} onChange={(event) => setEdit({ ...edit, edit_region: event.target.value })} /></Field>
                  <Field label="Exact change"><Textarea value={edit.change} onChange={(event) => setEdit({ ...edit, change: event.target.value })} /></Field>
                  <Field label="Do not introduce"><Textarea value={edit.do_not_introduce} onChange={(event) => setEdit({ ...edit, do_not_introduce: event.target.value })} /></Field>
                </div>
              )}

              {!colorsReady && <p className="text-xs text-red-700">Enter both a background and accent color.</p>}
              {sourceMode === "new" && imageEdit && !inlineReady && <p className="text-xs text-muted">Describe the exact image edit before generating an edit prompt.</p>}
              <Button className="w-full" onClick={() => void generate()} disabled={loading || !canGenerate}>
                {loading ? <Loader2 className="size-4 animate-spin" /> : <WandSparkles className="size-4" />}
                {loading ? "Generating…" : sceneReferencePath ? "Generate DINKLY universe adaptation" : sourceMode === "new" ? "Generate new concept prompt" : "Generate from saved concept"}
              </Button>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-3">
          <SceneCompleteness
            settingDefined={Boolean(sourceMode === "saved" ? selected?.left_setting && selected?.right_setting : inlineConcept.leftSetting && inlineConcept.rightSetting)}
            leftPropsDefined={Boolean(sourceMode === "saved" ? selected?.left_props?.length : split(inlineConcept.leftProps).length)}
            rightPropsDefined={Boolean(sourceMode === "saved" ? selected?.right_props?.length : split(inlineConcept.rightProps).length)}
            emotionalContrastDefined={Boolean(sourceMode === "saved" ? selected?.environmental_contrast || (selected?.left_emotion && selected?.right_emotion) : inlineConcept.environmentalContrast)}
            sharedEnvironmentDefined={Boolean(sourceMode === "saved" ? selected?.shared_environment : inlineConcept.sharedEnvironment)}
            characterSelectionDefined={Boolean(leftCharacter)}
          />
          <PromptPreview prompt={generated?.prompt ?? ""} rules={generated?.rules_included} sections={generated?.sections} />
          {generated && <SuggestedSpriteMotions topic={sourceMode === "saved" ? selected?.title_pair.left ?? "" : inlineConcept.leftTitle} />}
          {generated && (
            <div className="flex flex-wrap justify-end gap-2">
              <Button variant="outline" onClick={() => save("draft")}><Save className="size-4" />Mark as draft</Button>
              <Button onClick={() => save("approved")}><Save className="size-4" />Save approved prompt</Button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function SuggestedSpriteMotions({ topic }: { topic: string }) {
  const key = topic.toLowerCase();
  const suggestions = key.includes("coffee") ? ["Dinko soft breathing", "Dinka blink", "Coffee steam", "Floating hearts"]
    : key.includes("movie") ? ["Tiny lean", "Blink", "Television glow", "Popcorn bounce"]
      : key.includes("bed") || key.includes("nap") || key.includes("sleep") ? ["Soft breathing", "Slow blink", "Zzz marks"]
        : key.includes("party") ? ["Happy bounce", "Laugh", "Confetti", "Balloon bob"]
          : ["Soft breathing", "Blink", "Look toward each other", "Floating hearts"];
  return <div className="rounded-2xl border border-line bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">Suggested Sprite Motions</p><p className="mt-1 text-xs text-muted">Motion planning stays separate from the static Nano Banana prompt.</p></div><Button asChild size="sm" variant="outline"><Link href={`/sprite-studio/composer?suggestion=${encodeURIComponent(topic || "DINKLY scene")}`}><Layers3 className="size-4"/>Send to Composer</Link></Button></div><div className="mt-4 flex flex-wrap gap-2">{suggestions.map(item => <span key={item} className="rounded-full bg-wash px-3 py-1.5 text-xs font-semibold">{item}</span>)}</div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>;
}

function PresetOrCustomColor({ label, value, options, onChange, placeholder }: { label: string; value: string; options: readonly string[]; onChange: (value: string) => void; placeholder: string }) {
  const selectedValue = options.includes(value) ? value : "__custom__";
  return (
    <Field label={label}>
      <Select
        value={selectedValue}
        onChange={(event) => {
          if (event.target.value === "__custom__") {
            if (options.includes(value)) onChange("");
          } else {
            onChange(event.target.value);
          }
        }}
      >
        {options.map((option) => <option key={option} value={option}>{option}</option>)}
        <option value="__custom__">Custom color…</option>
      </Select>
      {selectedValue === "__custom__" && <Input aria-label={`Custom ${label.toLowerCase()}`} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} />}
    </Field>
  );
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <label className="flex items-center justify-between rounded-xl border border-line p-3 text-sm"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="size-4 accent-black" /></label>;
}

function CharacterButton({ label, detail, active, onClick }: { label: string; detail: string; active: boolean; onClick: () => void }) {
  return <button type="button" aria-pressed={active} onClick={onClick} className={`rounded-xl border p-3 text-left transition ${active ? "border-black bg-black text-white" : "border-line bg-white hover:bg-wash"}`}><span className="block text-sm font-semibold">{label}</span><span className={`mt-1 block text-xs ${active ? "text-white/65" : "text-muted"}`}>{detail}</span></button>;
}

function SceneCompleteness({ settingDefined, leftPropsDefined, rightPropsDefined, emotionalContrastDefined, sharedEnvironmentDefined, characterSelectionDefined }: { settingDefined: boolean; leftPropsDefined: boolean; rightPropsDefined: boolean; emotionalContrastDefined: boolean; sharedEnvironmentDefined: boolean; characterSelectionDefined: boolean }) {
  const checks = [
    ["Setting defined", settingDefined],
    ["Left props defined", leftPropsDefined],
    ["Right props defined", rightPropsDefined],
    ["Emotional contrast defined", emotionalContrastDefined],
    ["Shared environment defined", sharedEnvironmentDefined],
            ["Character selection defined", characterSelectionDefined],
  ] as const;
  return <div className="rounded-2xl border border-line bg-white p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold">Scene completeness</p><p className="mt-1 text-xs text-muted">Warnings guide the brief but never block generation.</p></div><span className="text-xs font-semibold text-muted">{checks.filter(([, complete]) => complete).length}/{checks.length}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{checks.map(([label, complete]) => <div key={label} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs ${complete ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-900"}`}>{complete ? <CheckCircle2 className="size-3.5" /> : <AlertCircle className="size-3.5" />}{label}</div>)}</div></div>;
}

function adaptLeftCopy(value: string, character: "boy" | "girl") {
  if (character === "girl") return value.replace(/Boy DINKLY/gi, "Girl DINKLY").replace(/Dinko/gi, "Dinka");
  return value.replace(/Girl DINKLY/gi, "Boy DINKLY").replace(/Dinka/gi, "Dinko");
}

function split(value: string) {
  return value.split(",").map((item) => item.trim()).filter(Boolean);
}
