"use client";

import { KeyRound, Play, RefreshCw, Save, Server } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { api } from "@/lib/api";

interface Worker { installed: boolean; running: boolean; status: string; heartbeat_at: string | null; mode: string; stdout_log: string; stderr_log: string }
interface Provider { configured: boolean; masked_token?: string | null; model: string; source?: string | null }
interface Automation { generate_daily_automatically: boolean; run_time: string; timezone: string; schedule_days: "every_day" | "weekdays"; catch_up_on_wake: boolean; catch_up_on_start: boolean; generate_on_start: boolean; enable_paid_model_calls: boolean; maximum_automatic_batch_cost: number; maximum_manual_batch_cost: number; daily_model_budget: number; monthly_model_budget: number; last_scheduler_check: string | null }

export function AgentOperationsSettings() {
  const [worker, setWorker] = useState<Worker>();
  const [provider, setProvider] = useState<Provider>();
  const [automation, setAutomation] = useState<Automation>();
  const [key, setKey] = useState("");
  const [model, setModel] = useState("gpt-5.6-luna");
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [nextWorker, nextProvider, nextAutomation] = await Promise.all([api<Worker>("/api/dinkly-agent/worker"), api<Provider>("/api/concept-generator/provider"), api<Automation>("/api/concept-generator/settings")]); setWorker(nextWorker); setProvider(nextProvider); setAutomation(nextAutomation); setModel(nextProvider.model || "gpt-5.6-luna"); }, []);
  useEffect(() => { load().catch(() => undefined); const poll = window.setInterval(() => load().catch(() => undefined), 5000); return () => window.clearInterval(poll); }, [load]);

  async function action(work: () => Promise<unknown>, success: string) { setBusy(true); try { await work(); toast.success(success); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "The Agent setting could not be changed"); } finally { setBusy(false); } }
  async function saveProvider() { if (!key.trim()) return; await action(() => api("/api/concept-generator/provider", { method: "PUT", body: JSON.stringify({ api_key: key, model }) }), "AI provider saved securely"); setKey(""); }
  async function saveAutomation() { if (!automation) return; await action(() => api("/api/concept-generator/settings", { method: "PUT", body: JSON.stringify({ ...automation, last_scheduler_check: null }) }), "Agent schedule and budgets saved"); }

  return <section className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-muted">DINKLY Agent</p><h2 className="mt-2 text-2xl font-semibold">Always-on work</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">The persistent worker owns the one task inbox. It waits at zero AI cost, wakes for assignments or schedules, and keeps working without an open browser.</p></div><div className="grid gap-5 lg:grid-cols-2">
    <Card><CardHeader><CardTitle className="flex items-center justify-between"><span className="flex items-center gap-2"><Server className="size-5"/>Always-on worker</span><State good={Boolean(worker?.running)} text={worker?.status ?? "Checking"}/></CardTitle></CardHeader><CardContent className="space-y-4"><Info label="Runtime mode" value={worker?.mode ?? "local"}/><Info label="Last heartbeat" value={worker?.heartbeat_at ? new Date(worker.heartbeat_at).toLocaleString() : "No heartbeat yet"}/><p className="text-xs leading-5 text-muted">During development, <strong>pnpm dev</strong> starts this worker with the API and web workspace. Install it to keep the local Agent active after Terminal closes.</p><div className="flex flex-wrap gap-2">{!worker?.installed && <Button onClick={() => void action(() => api("/api/dinkly-agent/worker/install", { method: "POST" }), "Always-on Agent installed")} disabled={busy}><Play className="size-4"/>Install worker</Button>}{worker?.installed && !worker.running && <Button onClick={() => void action(() => api("/api/dinkly-agent/worker/start", { method: "POST" }), "Agent started")} disabled={busy}><Play className="size-4"/>Start</Button>}<Button variant="outline" onClick={() => void action(() => api("/api/dinkly-agent/worker/restart", { method: "POST" }), "Agent restarted")} disabled={busy || !worker?.installed}><RefreshCw className="size-4"/>Restart</Button></div></CardContent></Card>
    <Card><CardHeader><CardTitle>AI provider</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-xs leading-5 text-muted">{provider?.configured ? `${provider.masked_token} · ${provider.model} · ${provider.source}` : "No text-model provider is configured. Concept assignments will stop before any paid call."}</p><Field label="OpenAI API key"><Input type="password" autoComplete="new-password" value={key} onChange={event => setKey(event.target.value)} placeholder={provider?.configured ? "Enter only to replace" : "sk-…"}/></Field><Field label="Model"><Input value={model} onChange={event => setModel(event.target.value)}/></Field><Button onClick={() => void saveProvider()} disabled={busy || !key.trim()}><KeyRound className="size-4"/>Save provider</Button></CardContent></Card>
    {automation && <Card className="lg:col-span-2"><CardHeader><CardTitle>Schedule and concept budgets</CardTitle></CardHeader><CardContent className="space-y-5"><Toggle label="Create daily concepts automatically" checked={automation.generate_daily_automatically} onChange={value => setAutomation({ ...automation, generate_daily_automatically: value })}/><div className="grid gap-4 sm:grid-cols-3"><Field label="Run time"><Input type="time" value={automation.run_time} onChange={event => setAutomation({ ...automation, run_time: event.target.value })}/></Field><Field label="Timezone"><Input value={automation.timezone} onChange={event => setAutomation({ ...automation, timezone: event.target.value })}/></Field><Field label="Days"><Select value={automation.schedule_days} onChange={event => setAutomation({ ...automation, schedule_days: event.target.value as Automation["schedule_days"] })}><option value="every_day">Every day</option><option value="weekdays">Weekdays</option></Select></Field></div><Toggle label="Allow paid model calls for scheduled concepts" checked={automation.enable_paid_model_calls} onChange={value => setAutomation({ ...automation, enable_paid_model_calls: value })}/><div className="grid gap-4 sm:grid-cols-4"><Money label="Automatic run max" value={automation.maximum_automatic_batch_cost} onChange={value => setAutomation({ ...automation, maximum_automatic_batch_cost: value })}/><Money label="Manual run max" value={automation.maximum_manual_batch_cost} onChange={value => setAutomation({ ...automation, maximum_manual_batch_cost: value })}/><Money label="Daily concept budget" value={automation.daily_model_budget} onChange={value => setAutomation({ ...automation, daily_model_budget: value })}/><Money label="Monthly concept budget" value={automation.monthly_model_budget} onChange={value => setAutomation({ ...automation, monthly_model_budget: value })}/></div><Button onClick={() => void saveAutomation()} disabled={busy}><Save className="size-4"/>Save schedule and budgets</Button></CardContent></Card>}
  </div></section>;
}

function State({ good, text }: { good: boolean; text: string }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${good ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-900"}`}>{text}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-wash p-3"><p className="text-[9px] font-bold uppercase tracking-wide text-muted">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between rounded-xl border border-line p-3 text-sm"><span>{label}</span><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} className="size-4 accent-black"/></label>; }
function Money({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <Field label={label}><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted">$</span><Input className="pl-7" type="number" min="0" step="0.1" value={value} onChange={event => onChange(Number(event.target.value))}/></div></Field>; }
