"use client";
import { createColumnHelper, flexRender, getCoreRowModel, getSortedRowModel, useReactTable, type SortingState } from "@tanstack/react-table";
import { ArrowUpDown } from "lucide-react";
import { useState } from "react";
import type { SocialPost } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

const column = createColumnHelper<SocialPost>();
const metric = (value: number | null) => value == null ? <span className="text-muted">Missing</span> : new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(value);
const rate = (value: number | null | undefined) => value == null ? <span className="text-muted">—</span> : `${(value * 100).toFixed(2)}%`;
const columns = [column.accessor("title", { header: "Post", cell: info => <div><p className="font-semibold">{info.getValue()}</p><p className="text-xs text-muted">{info.row.original.platform ?? "Platform missing"}</p></div> }), column.accessor("post_date", { header: "Date", cell: info => info.getValue() ?? <span className="text-muted">Missing</span> }), column.accessor("views", { header: "Views", cell: info => metric(info.getValue()) }), column.accessor("shares", { header: "Shares", cell: info => metric(info.getValue()) }), column.accessor(row => row.rates.share_rate, { id: "share_rate", header: "Share rate", cell: info => rate(info.getValue()) }), column.accessor("saves", { header: "Saves", cell: info => metric(info.getValue()) }), column.accessor(row => row.rates.save_rate, { id: "save_rate", header: "Save rate", cell: info => rate(info.getValue()) }), column.accessor(row => row.metric_completeness.percent, { id: "complete", header: "Metrics", cell: info => `${Math.round(info.getValue() * 100)}%` })];
export function SocialPostTable({ posts }: { posts: SocialPost[] }) { const [sorting, setSorting] = useState<SortingState>([{ id: "views", desc: true }]); const table = useReactTable({ data: posts, columns, state: { sorting }, onSortingChange: setSorting, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel() }); return <Table><TableHeader>{table.getHeaderGroups().map(group => <TableRow key={group.id}>{group.headers.map(header => <TableHead key={header.id}>{header.isPlaceholder ? null : <Button variant="ghost" size="sm" className="-ml-3" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}<ArrowUpDown className="size-3"/></Button>}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.map(row => <TableRow key={row.id}>{row.getVisibleCells().map(cell => <TableCell key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</TableCell>)}</TableRow>)}</TableBody></Table>; }
