"use client";

import { AlertTriangle, CheckCircle2, Copy, Trash2 } from "lucide-react";

import { spriteAssetUrl } from "@/lib/api";
import type { SpriteFrame } from "@/lib/types";
import { cn } from "@/lib/utils";

export function FrameThumbnail({ frame, selected, onSelect, onDuplicate, onRemove, draggable = true, onDragStart, onDrop }: { frame: SpriteFrame; selected: boolean; onSelect: (additive: boolean) => void; onDuplicate?: () => void; onRemove?: () => void; draggable?: boolean; onDragStart?: () => void; onDrop?: () => void }) {
  return <div draggable={draggable} onDragStart={onDragStart} onDragOver={event => event.preventDefault()} onDrop={onDrop} className={cn("group w-32 shrink-0 rounded-xl border bg-white p-2 transition", selected ? "border-ink ring-2 ring-mustard" : "border-line")}><button type="button" onClick={event => onSelect(event.shiftKey || event.metaKey)} className="block w-full"><div className="relative aspect-square rounded-lg bg-[linear-gradient(45deg,#eee_25%,transparent_25%),linear-gradient(-45deg,#eee_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#eee_75%),linear-gradient(-45deg,transparent_75%,#eee_75%)] bg-[length:14px_14px] bg-[position:0_0,0_7px,7px_-7px,-7px_0px]"><img src={spriteAssetUrl(frame.asset_url)} alt={`Frame ${frame.frame_index + 1}`} className="h-full w-full object-contain"/><span className="absolute left-1.5 top-1.5 rounded bg-black/70 px-1.5 py-0.5 text-[9px] font-bold text-white">{frame.frame_index + 1}</span>{frame.validation_warnings.length ? <AlertTriangle className="absolute right-1.5 top-1.5 size-3.5 text-orange-600"/> : frame.review_status === "Pass" ? <CheckCircle2 className="absolute right-1.5 top-1.5 size-3.5 text-emerald-600"/> : null}</div><p className="mt-2 text-[11px] font-semibold">{frame.duration_ms} ms</p><p className="truncate text-[10px] text-muted">{frame.review_status}</p></button>{(onDuplicate || onRemove) && <div className="mt-2 flex justify-end gap-1 border-t border-line pt-1.5">{onDuplicate && <button type="button" aria-label="Duplicate frame" onClick={onDuplicate} className="rounded p-1 text-muted hover:bg-wash"><Copy className="size-3"/></button>}{onRemove && <button type="button" aria-label="Remove frame" onClick={onRemove} className="rounded p-1 text-muted hover:bg-red-50 hover:text-red-700"><Trash2 className="size-3"/></button>}</div>}</div>;
}
