"use client";

import { ArrowDown, ArrowUp, Eye, EyeOff, Plus, Trash2 } from "lucide-react";

import { AnimationStateSelector } from "@/components/sprite-studio/animation-state-selector";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import type { SpriteAnimation, SpriteLayer } from "@/lib/types";

export function LayerComposer({ layers, animations, onChange }: { layers: SpriteLayer[]; animations: SpriteAnimation[]; onChange: (layers: SpriteLayer[]) => void }) {
  function update(id: string, values: Partial<SpriteLayer>) { onChange(layers.map(layer => layer.id === id ? { ...layer, ...values } : layer)); }
  function add() { const z = layers.length; onChange([...layers, { id: `layer-${Date.now()}`, layer_type: "effect", animation_id: null, label: "New layer", x: 0.5, y: 0.5, scale: 1, start_offset_ms: 0, z_index: z, visible: true, settings: {} }]); }
  function move(index: number, direction: number) { const target = index + direction; if (target < 0 || target >= layers.length) return; const copy = [...layers]; [copy[index], copy[target]] = [copy[target], copy[index]]; onChange(copy.map((layer, z_index) => ({ ...layer, z_index }))); }
  return <div className="space-y-3" data-testid="layer-composer">{layers.map((layer, index) => <div key={layer.id} className="rounded-xl border border-line bg-white p-3"><div className="flex items-center gap-2"><button type="button" aria-label="Toggle layer" onClick={() => update(layer.id, { visible: !layer.visible })} className="rounded p-1.5 hover:bg-wash">{layer.visible ? <Eye className="size-4"/> : <EyeOff className="size-4 text-muted"/>}</button><Input value={layer.label} onChange={event => update(layer.id, { label: event.target.value })} className="font-semibold"/><Button type="button" size="icon" variant="ghost" aria-label="Move layer up" onClick={() => move(index, -1)}><ArrowUp className="size-3"/></Button><Button type="button" size="icon" variant="ghost" aria-label="Move layer down" onClick={() => move(index, 1)}><ArrowDown className="size-3"/></Button><Button type="button" size="icon" variant="ghost" aria-label="Remove layer" onClick={() => onChange(layers.filter(item => item.id !== layer.id))}><Trash2 className="size-3"/></Button></div><div className="mt-3 grid gap-2 sm:grid-cols-5"><Select aria-label="Layer type" value={layer.layer_type} onChange={event => update(layer.id, { layer_type: event.target.value as SpriteLayer["layer_type"] })}><option>background</option><option>dinko</option><option>dinka</option><option>shared</option><option>prop</option><option>effect</option><option>foreground</option><option>text</option></Select><div className="sm:col-span-2"><AnimationStateSelector animations={animations.filter(animation => !["background", "text", "foreground"].includes(layer.layer_type) ? true : false)} value={layer.animation_id ?? ""} onChange={value => update(layer.id, { animation_id: value || null })} label="Select asset"/></div><Input aria-label="Layer X" type="number" min="0" max="1" step="0.01" value={layer.x} onChange={event => update(layer.id, { x: Number(event.target.value) })}/><Input aria-label="Layer Y" type="number" min="0" max="1" step="0.01" value={layer.y} onChange={event => update(layer.id, { y: Number(event.target.value) })}/><Input aria-label="Uniform scale" type="number" min="0.1" max="4" step="0.05" value={layer.scale} onChange={event => update(layer.id, { scale: Number(event.target.value) })}/><Input aria-label="Start offset" type="number" min="0" value={layer.start_offset_ms} onChange={event => update(layer.id, { start_offset_ms: Number(event.target.value) })}/></div></div>)}<Button type="button" variant="outline" onClick={add}><Plus className="size-4"/>Add layer</Button></div>;
}

